EVENT = 'event'
RAISED_BY = 'raised_by'
RECEIVED_BY = 'received_by'
ENTITY = 'entity'
ENTITY_CARDINALITY = 'entity_cardinality'
ATTRIBUTE = 'attribute'
ATTRIBUTE_CARDINALITY = 'attribute_cardinality'
ATTRIBUTE_TIMING = "attribute_timing"
SEMANTIC_TYPE = 'semantic_type'
DATA_CLASSIFICATION = 'classification'
DATA_VARIETY = 'variety'
SCHEMA_TYPE = 'schema_type'
COLUMN = 'column'
TABLE = 'table'
DATABASE = 'database'
NOT_NULL = 'not_null'
IS_UNIQUE = 'is_unique'
REFERENCE_COLUMN = 'reference_column'
REFERENCE_TABLE = 'reference_table'
REFERENCE_DATABASE = 'reference_database'

DBO = 'dbo'

OUTCOME = 'outcome'
RESULT = 'result'